# Credits

This is heavily influenced or copied from https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used. If you have a cuda enabled machine, read the README.md in the root of this repo on how to use nvidia-docker.


It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [4]:
import torch

Construct a 5x3 matrix, uninitialized

In [5]:
x = torch.Tensor(5, 3)
print(x)

tensor([[3.4511e-35, 0.0000e+00, 3.7835e-44],
        [0.0000e+00,        nan, 4.4842e-44],
        [1.3733e-14, 6.4069e+02, 4.3066e+21],
        [1.1824e+22, 4.3066e+21, 6.3828e+28],
        [3.8016e-39, 8.1546e-33, 1.3563e-19]])


Construct a randomly initialized matrix

In [6]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3671, 0.2038, 0.9529],
        [0.4903, 0.5220, 0.3474],
        [0.9639, 0.2176, 0.8205],
        [0.7310, 0.4602, 0.1101],
        [0.7114, 0.6619, 0.4041]])


Get its size

In [7]:
print(x.size())

torch.Size([5, 3])


**NOTE** `torch.Size` is in fact a tuple, so it supports the same operations

In [8]:
x[1:3] = 2
print(x)

tensor([[0.3671, 0.2038, 0.9529],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.7310, 0.4602, 0.1101],
        [0.7114, 0.6619, 0.4041]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [9]:
# 1. tensor of size (2,17)
tensor = torch.Tensor(2,17)
print("#1", tensor.size())

# 2. torch.FloatTensor of size (3,1)
tensor = torch.FloatTensor(3,1)
print("#2", tensor.size())

# 3. torch.LongTensor of size (5,2,1)
tensor = torch.LongTensor(5,2,1)
print("#3", tensor.size())
print(tensor)
# fill the entire tensor with 7s
tensor[:,:,:] = 7
print(tensor)

# 4. torch.ByteTensor of size (5,)
tensor = torch.ByteTensor(5,)
print("#4", tensor.size())
print(tensor)
# fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]
tensor[1:4] = 1
print(tensor)


#1 torch.Size([2, 17])
#2 torch.Size([3, 1])
#3 torch.Size([5, 2, 1])
tensor([[[   104220416],
         [206158430258]],

        [[206158430253],
         [193273528377]],

        [[223338299441],
         [210453397588]],

        [[249108103219],
         [206158430260]],

        [[210453397562],
         [197568495667]]])
tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]]])
#4 torch.Size([5])
tensor([  0, 126,  55,   6,   0], dtype=torch.uint8)
tensor([0, 1, 1, 1, 0], dtype=torch.uint8)


## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [10]:
y = torch.rand(5, 3)
print(x + y)

tensor([[1.2305, 0.2635, 1.3761],
        [2.5028, 2.5895, 2.0852],
        [2.2465, 2.3120, 2.0770],
        [0.9044, 0.5715, 0.6899],
        [0.7530, 0.6929, 1.3752]])


### 2.2 Addition: syntax 2

In [11]:
print(torch.add(x, y))

tensor([[1.2305, 0.2635, 1.3761],
        [2.5028, 2.5895, 2.0852],
        [2.2465, 2.3120, 2.0770],
        [0.9044, 0.5715, 0.6899],
        [0.7530, 0.6929, 1.3752]])


### 2.3 Addition: giving an output tensor

In [12]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.2305, 0.2635, 1.3761],
        [2.5028, 2.5895, 2.0852],
        [2.2465, 2.3120, 2.0770],
        [0.9044, 0.5715, 0.6899],
        [0.7530, 0.6929, 1.3752]])


### 2.4 Addition: in-place

adds `x`to `y`

In [13]:
y.add_(x)
print(y)

tensor([[1.2305, 0.2635, 1.3761],
        [2.5028, 2.5895, 2.0852],
        [2.2465, 2.3120, 2.0770],
        [0.9044, 0.5715, 0.6899],
        [0.7530, 0.6929, 1.3752]])


**NOTE** Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [14]:
print(x[:, 1])

tensor([0.2038, 2.0000, 2.0000, 0.4602, 0.6619])


**Read later** 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [15]:
# 1. multiplication of two tensors
print(torch.mul(x, y))

# 2. do the same, but inplace
x_copy = x
print(x_copy.mul_(y))

# 3. division of two tensors
print(torch.div(x, y))

# 4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)
print(torch.mm(torch.rand(2,4), torch.rand(4,2)))

tensor([[0.4517, 0.0537, 1.3113],
        [5.0057, 5.1790, 4.1705],
        [4.4931, 4.6241, 4.1539],
        [0.6612, 0.2630, 0.0760],
        [0.5357, 0.4587, 0.5557]])
tensor([[0.4517, 0.0537, 1.3113],
        [5.0057, 5.1790, 4.1705],
        [4.4931, 4.6241, 4.1539],
        [0.6612, 0.2630, 0.0760],
        [0.5357, 0.4587, 0.5557]])
tensor([[0.3671, 0.2038, 0.9529],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.7310, 0.4602, 0.1101],
        [0.7114, 0.6619, 0.4041]])
tensor([[0.6110, 0.5296],
        [1.3869, 0.8074]])


## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [16]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [17]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.

In [18]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [19]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a numpy array
3. now convert it back to a torch tensor

In [20]:
# 1. create a tensor of size (5, 2) containing ones
tensor = torch.ones(5,2)
print(tensor)

# 2. convert it to a numpy array
np_array = tensor.numpy()
print(np_array)

# 3. convert it back to a torch tensor
tensor = torch.from_numpy(np_array)
print(tensor)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [21]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # this is meant as a tensor to be run on the GPU.
    # the .cuda() does this to any parameter it is applied to
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")

tensor([[0.4517, 0.0537, 1.3113],
        [5.0057, 5.1790, 4.1705],
        [4.4931, 4.6241, 4.1539],
        [0.6612, 0.2630, 0.0760],
        [0.5357, 0.4587, 0.5557]], device='cuda:0')
tensor([[1.2305, 0.2635, 1.3761],
        [2.5028, 2.5895, 2.0852],
        [2.2465, 2.3120, 2.0770],
        [0.9044, 0.5715, 0.6899],
        [0.7530, 0.6929, 1.3752]], device='cuda:0')
tensor([[1.6822, 0.3173, 2.6875],
        [7.5085, 7.7685, 6.2557],
        [6.7396, 6.9361, 6.2309],
        [1.5656, 0.8345, 0.7659],
        [1.2887, 1.1516, 1.9309]], device='cuda:0')
